### ISSUE TITLE
install fails with node v4.x

### ISSUE THREAD

**Issue by jldec** [jldec/pub-server#1]
try to install with node v4

pub-server npm install will show errors building socket.io like the following:

```
> bufferutil@1.1.0 install /Users/hello/pub/server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
```

**Comment by jldec** [comment]
implemented temporary fix in pub-server v1.8.5 - expect permanent fix to land soon.
see https://github.com/socketio/socket.io/issues/2213

**Comment by tjwebb** [comment]
For projects like [sails.js](https://github.com/balderdashy/sails) which rely on socket.io as a dependency of the framework, we can't exactly resort to temporary hackery as easily as some applications can. We're very interested in seeing a fix published to npm soon.

**Comment by jldec** [comment]
[pub-server](https://github.com/jldec/pub-server) depends on socket.io. I didn't want pub-server users to have to fiddle with lower-level package.json entries when they install it, so i created a temporary workaround which allows them to install a working system under node v4. I decided that this was preferable to restricting all users to an earlier node version.

I have no connection with automattic, but i shared the workaround with the socket.io community, expecting that other package owners may want to do something similar.

I noticed that @rauchg was also active today on socket.io sub-projects.

**Comment by jldec** [comment]
just checked npm:
engine.io and engine.io-client have been updated to use ws 0.8 (which compiles on node v4)
but socket.io has not yet been updated on npm
so this temporary workaround is still required.
see socketio/socket.io#2213
j.
 
```
~$ npm info socket.io version dependencies 
version = '1.3.6'
dependencies =  
{ 'engine.io': '1.5.2',
  'socket.io-parser': '2.2.4',
  'socket.io-client': '1.3.6',
  'socket.io-adapter': '0.3.1',
  'has-binary-data': '0.1.3',
  debug: '2.1.0' }

~$ npm info engine.io version dependencies 
version = '1.5.4'
dependencies =  
{ base64id: '0.1.0',
  debug: '1.0.3',
  'engine.io-parser': '1.2.2',
  ws: '0.8.0' }

~$ npm info socket.io-client version dependencies 
version = '1.3.6'
dependencies =  
{ debug: '0.7.4',
  'engine.io-client': '1.5.2',
  'component-bind': '1.0.0',
  'component-emitter': '1.1.2',
  'object-component': '0.0.3',
  'socket.io-parser': '2.2.4',
  'has-binary': '0.1.6',
  indexof: '0.0.1',
  parseuri: '0.0.2',
  'to-array': '0.1.3',
  backo2: '1.0.2' }

~$ npm info engine.io-client version dependencies 
version = '1.5.4'
dependencies =  
{ 'component-emitter': '1.1.2',
  'component-inherit': '0.0.3',
  debug: '1.0.4',
  'engine.io-parser': '1.2.2',
  'has-cors': '1.0.3',
  indexof: '0.0.1',
  parsejson: '0.0.1',
  parseqs: '0.0.2',
  parseuri: '0.0.4',
  ws: '0.8.0',
  xmlhttprequest: 'https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz' }
```

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by jldec** [comment]
fixed with socket.io v1.3.7
