### ISSUE TITLE
markdown fragments in sub-directories

### ISSUE THREAD

**Issue by davidmoshal** [jldec/pub-server#2]
hi, am wondering if it's possible to point pub at a directory and have it parse sub directories, generating a navigation tree automatically??

Thanks

David

**Comment by jldec** [comment]
Hi David,

Yes, all the mechanics are there for that - the default reader will recurse directories to a configurable depth and generate a url hierarchy from directories/filenames. This hierarchy can be rendered to an HTML ul/li structure with the {{{pagetree}}} helper.

I haven't actually released a theme which uses this - the default pub-theme-doc package renders pages in a flat list - but it should be easy to try out.

hth
j.
